### ISSUE TITLE
Where download WinLdtpdService.exe

### ISSUE THREAD

**Issue by radici** [majorsilence/Dev#14]
Where download WinLdtpdService.exe
Thanks

**Comment by majorsilence** [comment]
Maybe from https://github.com/ldtp/cobra/releases.  Not sure anymore.

**Comment by radici** [comment]
HI thanks for your time but this file is not inside the .msi installation program neither inside the source code.
Thanks

**Comment by amaljesudas** [comment]
Hi radici ,

Where you able to find the same?
I am new to LDTP, was searching how to set up the environment in Windows 10.
Came across the same doubt as you.
Any help is appreciated.
Thanks in advance.

Regards,
Amal
